version: '3.4'

services:
  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: Products.API/Dockerfile

networks:
  eszop-network:
    external: true